spring:
  datasource:
    url: jdbc:h2:mem:sa
    username: sa
    password:

  jpa:
    show-sql: true  # Exibe as queries SQL no console
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true  # Ativa o console do H2
      path: /h2-console  # Caminho do console
      settings:
        trace: false
        web-allow-others: false